version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  scheduler:
    build:
      context: ./scheduler_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./scheduler_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./scheduler_service/.env
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: ./scheduler_service
    entrypoint: celery
    command: -A celery_worker.app worker --loglevel=info
    volumes:
      - ./scheduler_service:/app
    env_file:
      - ./scheduler_service/.env
    depends_on:
      - redis

  beat:
    build:
      context: ./scheduler_service
    entrypoint: celery
    command: -A celery_worker.app beat --loglevel=info
    volumes:
      - ./scheduler_service:/app
    env_file:
      - ./scheduler_service/.env
    depends_on:
      - redis

  executor:
    build:
      context: ./task_executor_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./task_executor_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./task_executor_service/.env
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
