"""max_retry

Revision ID: a4f5db6ecebc
Revises: bfc388cd47b2
Create Date: 2026-05-28 03:00:06.943965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f5db6ecebc'
down_revision: Union[str, Sequence[str], None] = 'bfc388cd47b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definitions', sa.Column('max_retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_definitions', 'max_retries')
    # ### end Alembic commands ###
