"""Initial migration

Revision ID: bfc388cd47b2
Revises: 
Create Date: 2026-05-28 01:48:36.470039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc388cd47b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_definitions_id'), 'task_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_task_definitions_name'), 'task_definitions', ['name'], unique=True)
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id', sa.Integer(), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('polling_url', sa.String(), nullable=True),
    sa.Column('task_logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_task_definitions_name'), table_name='task_definitions')
    op.drop_index(op.f('ix_task_definitions_id'), table_name='task_definitions')
    op.drop_table('task_definitions')
    # ### end Alembic commands ###
